---
- name: Install IIS on windows servers
  hosts: winserver
  tasks:
    - name: Install IIS (Web-Server only)
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: true
        include_management_tools: true
      register: win_feature