---
- name: Install IIS on windows servers
  hosts: winserver
  tasks:
    - name: Install IIS (Web-Server only)
      ansible.windows.win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: present  